version: '3.1'

services:
  wordpress:
    image: wp-site:latest
    env_file: 
      - .env
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress: