FROM wordpress:5.6.0-php7.4

ENV WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST \
    WORDPRESS_DB_USER=$WORDPRESS_DB_USER \
    WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD \
    WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME \
    WORDPRESS_TABLE_PREFIX=$WORDPRESS_TABLE_PREFIX